"""Terraform parser — tfstate + plan JSON, with sourcing helpers.

Supports:
- `terraform.tfstate` (v4 JSON format) — local path or s3:// URI
- `terraform show -json plan.bin` (plan JSON) — local path
- Directory of `.tf` files — runs terraform init+plan+show internally

Each parsed resource carries: tf_type, address (with module path and instance key),
and the resolved attributes. Module roots, count, and for_each are flattened to
one entry per instance.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from collections.abc import Iterator
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import boto3
import structlog

from cenote.catalogs.resource_types import is_supported
from cenote.core.arn import tf_to_arn
from cenote.core.models import TFState

log = structlog.get_logger()


class TerraformError(RuntimeError):
    """Raised when terraform sourcing fails (download, init, plan)."""


def fetch_tfstate(uri: str, profile: str | None = None) -> Path:
    """Resolve a tfstate source to a local file path.

    Accepts:
      - local path (already a file)
      - `s3://bucket/key` URI (downloaded with the same AWS session as the scanner)

    The caller is responsible for cleaning up if it was downloaded.
    """
    parsed = urlparse(uri)
    if parsed.scheme in ("", "file"):
        p = Path(parsed.path or uri)
        if not p.exists():
            raise TerraformError(f"tfstate not found at {p}")
        return p
    if parsed.scheme == "s3":
        if not parsed.netloc or not parsed.path:
            raise TerraformError(f"invalid s3 URI: {uri}")
        session = boto3.Session(profile_name=profile) if profile else boto3.Session()
        s3 = session.client("s3")
        bucket = parsed.netloc
        key = parsed.path.lstrip("/")
        fd, dest_str = tempfile.mkstemp(suffix=".tfstate")
        os.close(fd)
        dest = Path(dest_str)
        try:
            s3.download_file(bucket, key, str(dest))
        except Exception as exc:
            dest.unlink(missing_ok=True)
            raise TerraformError(f"failed to download {uri}: {exc}") from exc
        log.info("tfstate.s3.downloaded", uri=uri, dest=str(dest))
        return dest
    raise TerraformError(f"unsupported tfstate URI scheme: {parsed.scheme}")


_OFFLINE_OVERRIDE_TF = """\
# Auto-generated by Cenote. Skips every call the AWS provider would normally
# make during init/plan so a diagram can be rendered without credentials.
# Merged into the user's `provider "aws" {}` block via terraform's *_override.tf
# convention; harmless if no such block exists.
provider "aws" {
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  skip_region_validation      = true
}
"""

# `__REGION__` is substituted with str.replace (not str.format) — the body is
# HCL full of literal braces, so format-style escaping is error-prone.
_OFFLINE_BASELINE_TF_TEMPLATE = """\
# Auto-generated by Cenote. Only injected when the uploaded code has no
# provider "aws" block, so terraform plan has something to initialize.
provider "aws" {
  region                      = "__REGION__"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  skip_region_validation      = true
}
"""


def _inject_offline_provider(directory: Path, region: str) -> None:
    """Write the override + (conditionally) baseline provider into `directory`.

    Files are prefixed with `_cenote_` so they're easy to spot if anything
    goes wrong and the temp dir survives.
    """
    (directory / "_cenote_override.tf").write_text(_OFFLINE_OVERRIDE_TF)

    has_user_provider = any(
        'provider "aws"' in tf_file.read_text(encoding="utf-8", errors="replace")
        for tf_file in directory.rglob("*.tf")
        if tf_file.name != "_cenote_override.tf"
    )
    if not has_user_provider:
        (directory / "_cenote_baseline_provider.tf").write_text(
            _OFFLINE_BASELINE_TF_TEMPLATE.replace("__REGION__", region)
        )


def _strip_hcl_quotes(s: object) -> str:
    if not isinstance(s, str):
        return str(s)
    if len(s) >= 2 and s[0] == s[-1] == '"':
        return s[1:-1]
    return s


# Name-based heuristics for AWS fields that fail provider validation if fed
# a nonsense string (CIDR, AMI, region, …). Substring-matched against the
# lower-cased variable name. Order matters: more specific keys first.
_SCALAR_HEURISTICS: list[tuple[str, str]] = [
    ("cidr", "10.0.0.0/16"),
    ("availability_zone", "us-east-1a"),
    ("ami", "ami-0abcdef1234567890"),
    ("subnet", "subnet-0abcdef1234567890"),
    ("vpc", "vpc-0abcdef1234567890"),
    ("security_group", "sg-0abcdef1234567890"),
    ("region", "us-east-1"),
    ("instance_type", "t3.micro"),
    ("account_id", "000000000000"),
    ("account", "000000000000"),
    ("arn", "arn:aws:iam::000000000000:role/cenote-placeholder"),
    ("email", "noreply@example.com"),
    ("bucket", "cenote-placeholder-bucket"),
    ("domain", "example.com"),
    ("kms_key", "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000000"),
]


def _scalar_placeholder(name: str) -> str:
    low = name.lower()
    for key, value in _SCALAR_HEURISTICS:
        if key in low:
            return value
    return "cenote-auto"


# `condition = …` up to the `error_message` line or the validation block's
# closing brace. DOTALL so multi-line `||` conditions are captured whole.
_CONDITION_RE = re.compile(
    r"condition\s*=\s*(.*?)(?:\n[ \t]*error_message|\n[ \t]*\})",
    re.DOTALL,
)


def _validation_allowed_value(block_body: str) -> str | None:
    """Best-effort: derive a value that SATISFIES a variable's `validation`
    condition, for the common allow-list shapes that otherwise reject our
    generic placeholder:

        contains(["dev", "prod"], var.environment)
        var.environment == "dev" || var.environment == "prod"

    Returns the first allowed string literal. Returns None when the condition
    is a regex / negation / numeric check we can't satisfy by plucking a
    literal (those would pick a *forbidden* value or a regex pattern) — the
    name heuristics then apply instead.
    """
    m = _CONDITION_RE.search(block_body)
    if not m:
        return None
    cond = m.group(1)
    # `!=` / `!contains` → the literal is forbidden, not allowed.
    # `regex(`/`can(` → the literal is a pattern, not a value.
    if "!=" in cond or "!contains" in cond or "regex(" in cond or "can(" in cond:
        return None
    for lit in re.findall(r'"([^"]*)"', cond):
        if lit:  # skip empty-string literals (usually a "must not be empty" check)
            return lit
    return None


def _placeholder_literal(
    name: str, type_expr: object, allowed_value: str | None = None
) -> str:
    """A synthetic value for a required variable, as a string suitable for a
    `TF_VAR_<name>` env var. Terraform parses non-string env values as HCL,
    so `[]` / `{}` / `1` / `false` round-trip into the declared type.

    Precedence for scalars: an `allowed_value` mined from a `validation`
    block (so enum constraints like `dev|prod` pass) wins over name heuristics
    (`*cidr*` → a real CIDR, etc.), which win over the generic placeholder.
    The AWS provider and custom validations both reject garbage strings at
    plan time, so getting this right keeps the plan from aborting."""
    t = _strip_hcl_quotes(type_expr or "").strip()
    if t.startswith("${") and t.endswith("}"):
        t = t[2:-1].strip()
    if t.startswith(("map", "object")):
        return "{}"
    if t.startswith(("list", "set", "tuple")):
        # A single-element collection with a sensible scalar; empty lists make
        # `element()`/index lookups fail, so we seed one item.
        scalar = allowed_value or _scalar_placeholder(name)
        return f'["{scalar}"]'
    if t == "number":
        return "1"
    if t == "bool":
        return "false"
    return allowed_value or _scalar_placeholder(name)  # string, any, or undeclared


_VAR_BLOCK_RE = re.compile(r'variable\s+"([^"]+)"\s*\{')
_DEFAULT_RE = re.compile(r"(?:^|\n)[ \t]*default[ \t]*=")
_TYPE_RE = re.compile(r"(?:^|\n)[ \t]*type[ \t]*=[ \t]*(.+)")


def _iter_variable_blocks(text: str) -> Iterator[tuple[str, str]]:
    """Yield (name, block_body) for every `variable "x" { … }` in `text`,
    using brace counting so `validation {}` blocks and `object({…})` types
    don't terminate the block early.

    We scan with a regex instead of python-hcl2 because hcl2 throws on
    perfectly valid HCL it doesn't fully support (custom validation messages,
    `optional()` in object types, heredocs). A parse failure there silently
    dropped every variable in the file, so terraform plan then aborted on the
    first one — exactly the bug this avoids.
    """
    for m in _VAR_BLOCK_RE.finditer(text):
        depth = 1
        i = m.end()
        n = len(text)
        while i < n and depth:
            ch = text[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            i += 1
        yield m.group(1), text[m.end():i - 1]


def _required_var_placeholders(directory: Path) -> dict[str, str]:
    """Return `TF_VAR_<name>` entries for ROOT variables that have no `default`.

    Many real projects keep required variables and feed them from a tfvars
    file or CI pipeline that isn't part of the uploaded zip. Without values,
    `terraform plan -input=false` aborts with "No value for required
    variable". We auto-fill placeholders via TF_VAR_* (the LOWEST-precedence
    source) so a genuine `terraform.tfvars` in the upload still wins.

    Only top-level `.tf` files are scanned — child-module variables get their
    values from the module call, not from root tfvars.
    """
    out: dict[str, str] = {}
    for tf_file in sorted(directory.glob("*.tf")):  # non-recursive: root only
        if tf_file.name.startswith("_cenote_"):
            continue
        try:
            text = tf_file.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            log.warning("terraform.var_scan.read_fail", file=tf_file.name, error=str(exc))
            continue
        for name, body in _iter_variable_blocks(text):
            if _DEFAULT_RE.search(body):
                continue  # has a default → terraform supplies it
            type_match = _TYPE_RE.search(body)
            type_expr = type_match.group(1).strip() if type_match else None
            allowed = _validation_allowed_value(body)
            out[f"TF_VAR_{name}"] = _placeholder_literal(name, type_expr, allowed)
    return out


def run_terraform_plan_offline(directory: Path) -> Path:
    """`terraform init -backend=false` + `plan -refresh=false` + `show -json`,
    fully offline (no remote backend, no AWS API calls).

    Used by the TF-diagram endpoint: the user uploads raw .tf, we want a
    fully-expanded plan (modules, count, for_each, variables resolved) WITHOUT
    requiring AWS credentials or a real backend. `data` source blocks may
    still fail if they need credentials — that error surfaces verbatim in
    the HTTPException raised by the caller, so the user knows to remove
    them or switch to creds mode.

    Returns the path to the `show -json` JSON output.
    """
    if not shutil.which("terraform"):
        raise TerraformError(
            "terraform binary not found in PATH. The api container ships it; "
            "if you're running locally, install terraform 1.5+."
        )
    if not directory.exists() or not directory.is_dir():
        raise TerraformError(f"directory does not exist: {directory}")
    if not any(directory.rglob("*.tf")):
        raise TerraformError(f"no .tf files under {directory}")

    # Stub AWS env so the provider can initialize. The skip_* flags actually
    # take effect via the injected override file below — AWS provider 5.x
    # ignores most of these env vars otherwise.
    env = {
        **os.environ,
        "AWS_ACCESS_KEY_ID": "AKIA00000000DIAGRAM0",
        "AWS_SECRET_ACCESS_KEY": "0000000000000000000000000000000000000000",
        "AWS_REGION": os.environ.get("AWS_REGION", "us-east-1"),
        "AWS_DEFAULT_REGION": os.environ.get("AWS_REGION", "us-east-1"),
        # Suppress the upgrade nag and don't ask interactive questions.
        "TF_IN_AUTOMATION": "1",
        "CHECKPOINT_DISABLE": "1",
    }

    # Inject provider config so plan never calls AWS. Two files:
    #   1. *_override.tf — merged into the user's `provider "aws" {}` block
    #      (no-op if the user doesn't have one).
    #   2. cenote_baseline_provider.tf — only written if the user declared no
    #      `provider "aws"` block, so terraform still has something to init.
    _inject_offline_provider(directory, env["AWS_REGION"])

    # Auto-fill required root variables (no default) so `plan -input=false`
    # doesn't abort. TF_VAR_* is the lowest-precedence source, so a real
    # terraform.tfvars in the upload still overrides these placeholders.
    placeholders = _required_var_placeholders(directory)
    if placeholders:
        env.update(placeholders)
        log.info("terraform.offline.var_placeholders", count=len(placeholders))

    def _run(args: list[str], step: str) -> subprocess.CompletedProcess[str]:
        log.info("terraform.offline.run", step=step, args=args)
        return subprocess.run(
            ["terraform", *args],
            cwd=str(directory),
            capture_output=True,
            text=True,
            env=env,
            check=False,
        )

    init = _run(
        ["init", "-backend=false", "-input=false", "-no-color"],
        "init",
    )
    if init.returncode != 0:
        tail = (init.stderr or init.stdout or "").splitlines()[-15:]
        raise TerraformError("terraform init failed:\n" + "\n".join(tail))

    plan_bin = directory / ".terraform" / "cenote.tfplan"
    plan_bin.parent.mkdir(parents=True, exist_ok=True)
    plan = _run(
        [
            "plan",
            "-input=false",
            "-no-color",
            "-refresh=false",
            "-lock=false",
            "-out",
            str(plan_bin),
        ],
        "plan",
    )
    if plan.returncode != 0:
        tail = (plan.stderr or plan.stdout or "").splitlines()[-20:]
        raise TerraformError("terraform plan failed:\n" + "\n".join(tail))

    show = _run(["show", "-json", str(plan_bin)], "show")
    if show.returncode != 0:
        raise TerraformError(f"terraform show -json failed: {show.stderr[:500]}")

    plan_json = directory / ".terraform" / "cenote.plan.json"
    plan_json.write_text(show.stdout)
    log.info("terraform.offline.ok", json_path=str(plan_json))
    return plan_json


def run_terraform_plan(directory: Path, extra_env: dict[str, str] | None = None) -> Path:
    """Run `terraform init` + `plan` + `show -json` in `directory`. Returns plan-JSON path.

    Honors existing `*.tfvars` / `*.auto.tfvars` in the dir and `TF_VAR_*` env vars.
    The plan binary and JSON are written under `<dir>/.terraform/`.
    """
    if not shutil.which("terraform"):
        raise TerraformError(
            "terraform binary not found in PATH. Rebuild the api container "
            "(it ships terraform by default)."
        )
    if not directory.exists() or not directory.is_dir():
        raise TerraformError(f"directory does not exist: {directory}")
    if not any(directory.glob("*.tf")):
        raise TerraformError(f"no .tf files in {directory}")

    proc_env = {**os.environ, **(extra_env or {})}

    def _run(args: list[str], step: str) -> subprocess.CompletedProcess[str]:
        log.info("terraform.run", step=step, args=args)
        return subprocess.run(
            ["terraform", *args],
            cwd=str(directory),
            capture_output=True,
            text=True,
            env=proc_env,
            check=False,
        )

    init = _run(["init", "-input=false", "-no-color"], "init")
    if init.returncode != 0:
        tail = (init.stderr or init.stdout or "").splitlines()[-15:]
        raise TerraformError("terraform init failed:\n" + "\n".join(tail))

    plan_bin = directory / ".terraform" / "cenote.tfplan"
    plan_bin.parent.mkdir(parents=True, exist_ok=True)
    plan = _run(
        ["plan", "-input=false", "-no-color", "-out", str(plan_bin)],
        "plan",
    )
    if plan.returncode != 0:
        tail = (plan.stderr or plan.stdout or "").splitlines()[-15:]
        raise TerraformError("terraform plan failed:\n" + "\n".join(tail))

    show = _run(["show", "-json", str(plan_bin)], "show")
    if show.returncode != 0:
        raise TerraformError(f"terraform show -json failed: {show.stderr[:500]}")

    plan_json = directory / ".terraform" / "cenote.plan.json"
    plan_json.write_text(show.stdout)
    log.info("terraform.plan.ok", json_path=str(plan_json))
    return plan_json


class ParsedTFResource:
    """A single TF resource instance (one per count/for_each expansion)."""

    __slots__ = ("tf_type", "address", "module", "attributes", "name", "instance_key")

    def __init__(
        self,
        tf_type: str,
        address: str,
        module: str | None,
        name: str,
        attributes: dict[str, Any],
        instance_key: Any = None,
    ) -> None:
        self.tf_type = tf_type
        self.address = address
        self.module = module
        self.name = name
        self.attributes = attributes
        self.instance_key = instance_key

    def to_tf_state(self) -> TFState:
        return TFState(address=self.address, module=self.module, attributes=self.attributes)


def parse_tfstate(path: Path) -> list[ParsedTFResource]:
    """Parse a terraform.tfstate v4 file."""
    raw = json.loads(path.read_text())
    return _parse_state_json(raw)


def parse_plan_json(path: Path) -> list[ParsedTFResource]:
    """Parse a `terraform show -json plan.bin` output."""
    raw = json.loads(path.read_text())
    # plan JSON has `planned_values.root_module` (post-apply state)
    pv = raw.get("planned_values") or {}
    return _walk_plan_module(pv.get("root_module") or {}, module_path=None)


def _parse_state_json(state: dict[str, Any]) -> list[ParsedTFResource]:
    out: list[ParsedTFResource] = []
    for res in state.get("resources", []):
        if res.get("mode") != "managed":
            continue
        tf_type = res.get("type")
        if not tf_type or not is_supported(tf_type):
            continue
        name = res.get("name") or tf_type
        module = res.get("module")  # e.g. "module.api" or None
        for inst in res.get("instances", []):
            attrs = inst.get("attributes") or {}
            instance_key = inst.get("index_key")
            address = _build_address(module, tf_type, name, instance_key)
            out.append(ParsedTFResource(
                tf_type=tf_type,
                address=address,
                module=module,
                name=name,
                attributes=attrs,
                instance_key=instance_key,
            ))
    return out


def _walk_plan_module(module: dict[str, Any], module_path: str | None) -> list[ParsedTFResource]:
    out: list[ParsedTFResource] = []
    for res in module.get("resources", []):
        if res.get("mode") != "managed":
            continue
        tf_type = res.get("type")
        if not tf_type or not is_supported(tf_type):
            continue
        out.append(ParsedTFResource(
            tf_type=tf_type,
            address=res.get("address") or f"{tf_type}.{res.get('name')}",
            module=module_path,
            name=res.get("name") or tf_type,
            attributes=res.get("values") or {},
            instance_key=res.get("index"),
        ))
    for child in module.get("child_modules", []):
        out.extend(_walk_plan_module(child, child.get("address")))
    return out


def _build_address(module: str | None, tf_type: str, name: str, key: Any) -> str:
    base = f"{tf_type}.{name}"
    if module:
        base = f"{module}.{base}"
    if key is None:
        return base
    if isinstance(key, int):
        return f"{base}[{key}]"
    return f'{base}["{key}"]'


def resolve_arn(parsed: ParsedTFResource, account_id: str, region: str) -> str | None:
    """Map a parsed TF resource to its canonical AWS ARN."""
    return tf_to_arn(parsed.tf_type, parsed.attributes, account_id, region)
